### ISSUE TITLE
help error

### ISSUE THREAD

**Issue by gofursp** [s0md3v/infinity#5]
help me with error

`Traceback (most recent call last):
  File "infinity.py", line 117, in <module>
    limits(count)
  File "infinity.py", line 59, in limits
    return int(''.join(limit))
ValueError: invalid literal for int() with base 10: ''`

**Comment by s0md3v** [comment]
As the README declares, it doesn't work anymore.

**Comment by xunuuth19** [comment]
please restore it...it is very important for me to find a phone number...

**Comment by s0md3v** [comment]
Facebook patched the vulnerability.
